server:
  port: 8886
  ssl:
    enabled: true
    key-store-type: jks
    key-store: /Users/hakurei/Projects/hello-kafka/http-ssl/configuration-service/configuration-service-server.jks
    key-store-password: 123456
    key-alias: configuration-service-server
    trust-store: /Users/hakurei/Projects/hello-kafka/http-ssl/configuration-service/configuration-service-server.jks
    trust-store-password: 123456
    trust-store-type: jks
    client-auth: need
    trust-store-provider: SUN

hibernate:
  connection:
    url: jdbc:postgresql://localhost:5432/default?currentSchema=config
    username: sigreen
    password: 123456

spring:
  datasource:
    url: ${hibernate.connection.url}
    username: ${hibernate.connection.username}
    password: ${hibernate.connection.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto:
        show_sql: true
        multiTenancy: DATABASE
        tenant_identifier_resolver: com.siemens.multitenancy.configuration.hibernate.multitenancy.TenantIdentifierResolver
        multi_tenant_connection_provider: com.siemens.multitenancy.configuration.hibernate.multitenancy.SchemaMultiTenantConnectionProvider
  flyway:
    enabled: false

flyway:
  url: ${hibernate.connection.url}
  user: ${hibernate.connection.username}
  password: ${hibernate.connection.password}
  baselineOnMigrate: true