server:
  port: 8886

hibernate:
  connection:
    url: jdbc:h2:mem:h2
    username: sigreen
    password: 123456

spring:
  datasource:
    url: ${hibernate.connection.url}
    username: ${hibernate.connection.username}
    password: ${hibernate.connection.password}
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

flyway:
  url: ${hibernate.connection.url}
  user: ${hibernate.connection.username}
  password: ${hibernate.connection.password}
  baselineOnMigrate: true