server:
  port: 8886

hibernate:
  connection:
    url: jdbc:postgresql://localhost:5432/default?currentSchema=config
    username: sigreen
    password: 123456

spring:
  datasource:
    url: ${hibernate.connection.url}
    username: ${hibernate.connection.username}
    password: ${hibernate.connection.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto:
        show_sql: true
        multiTenancy: DATABASE
        tenant_identifier_resolver: com.siemens.multitenancy.configuration.hibernate.multitenancy.TenantIdentifierResolver
        multi_tenant_connection_provider: com.siemens.multitenancy.configuration.hibernate.multitenancy.SchemaMultiTenantConnectionProvider
  flyway:
    enabled: false

flyway:
  url: ${hibernate.connection.url}
  user: ${hibernate.connection.username}
  password: ${hibernate.connection.password}
  baselineOnMigrate: true