openapi: 3.0.0
info:
  title: Message handler
  version: v0
servers:
- {}
paths:
  /api/v1/configuration/manager/register:
    post:
      operationId: register
      parameters:
      - description: TenantId.
        explode: true
        in: query
        name: tenantId
        required: true
        schema:
          type: string
        style: form
      - description: IConnector ID.
        explode: true
        in: query
        name: connectorId
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: '104: Send iConnector configuration to MQ'
      tags:
      - i-connector-register-controller
      x-contentType: application/json
      x-accepts: application/json
  /iconnector-config.%s-%s:
    post:
      operationId: send iConnector configuration to iConnector
      parameters:
      - description: topic
        explode: true
        in: query
        name: topic
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: '105: Send iConnector configuration to iConnector'
      tags:
      - kafka-producer
      x-contentType: application/json
      x-accepts: application/json
  /iconnector-info.*:
    get:
      operationId: get iConnector info from MQ
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
      summary: '108: get iConnector info from MQ'
      tags:
      - kafka-consumer
      x-contentType: application/json
      x-accepts: application/json
  /iconnector-data.*:
    get:
      operationId: get data from MQ
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
      summary: '106: get data from MQ'
      tags:
      - kafka-consumer
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object

