version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

#  multi-tenancy:
#    build: .
#    container_name: multi-tenancy
#    restart: always
#    image: multi-tenancy:1.0
#    ports:
#      - "8886:8886"
#    depends_on:
#      - kafka
#      - postgres
#    links:
#      - kafka
#      - postgres
#    tty: true
#    volumes:
#      - ./ssl:/certs/