version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: sigreen
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

#  configuration-service:
#    build: .
#    container_name: configuration-service
#    hostname: configuration-service
#    restart: always
#    image: configuration-service:1.0.0
#    ports:
#      - "8886:8886"
#    depends_on:
#      - postgres
#    links:
#      - postgres
#    tty: true