version: '3'

services:
  iconnector:
    build: .
    container_name: iconnector
    hostname: iconnector
    restart: always
    image: iconnector:1.0.0
    ports:
      - "8888:8888"
    depends_on:
      - kafka
    links:
      - kafka
    tty: true
    volumes:
      - ./ssl:/certs/