openapi: 3.0.0
info:
  title: Configuration service
  version: v0
servers:
  - url: ''
paths:
  /api/v1/iconnector/updateConnectorInfo:
    put:
      summary: '101: Return the iConnector info which update'
      tags:
        - i-connect-controller
      operationId: updateConnectorInfo
      parameters:
        - name: X-TENANT-ID
          in: header
          description: 'The tenant ID.'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientUpdateParam'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/IConnectorInfoVo'
        default:
          description: 'Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/iconnector/info:
    post:
      summary: '109: Receive and update iConnector infos send by iConnector'
      tags:
        - i-connect-controller
      operationId: connectorInfo
      parameters:
        - name: X-TENANT-ID
          in: header
          description: 'The tenant ID.'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IConnectorInfoParam'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
        default:
          description: 'Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/iconnector/register:
    get:
      summary: '103: Send configuration of iConnector to message-handler'
      tags:
        - i-connect-controller
      operationId: registerConnector
      parameters:
        - name: X-TENANT-ID
          in: header
          description: 'The tenant ID.'
          required: true
          schema:
            type: string
        - name: connectorId
          in: query
          description: 'The iConnector ID.'
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
        default:
          description: 'Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/iconnector/getConnectorInfos:
    get:
      summary: '101: Get all iConnector infos'
      tags:
        - i-connect-controller
      operationId: getConnectorInfos
      parameters:
        - name: X-TENANT-ID
          in: header
          description: 'The tenant ID.'
          required: true
          schema:
            type: string
        - name: clientQueryParam
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ClientQueryParam'
        - name: pageParam
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/PageParam'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IConnectorInfoVo'
        default:
          description: 'Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ClientUpdateParam:
      type: object
      properties:
        connectorId:
          type: string
          description: 'The iConnector ID.'
        configs:
          type: array
          description: 'The iConnector configs'
          items:
            $ref: '#/components/schemas/Config'
    Config:
      type: object
    IConnectorConfig:
      type: object
      properties:
        id:
          type: integer
          format: int64
    IConnectorInfoVo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        connectorId:
          type: string
        status:
          type: integer
          format: int32
        collectStatus:
          type: integer
          format: int32
        version:
          type: string
        dateTime:
          type: string
          format: date-time
        modules:
          type: array
          items:
            $ref: '#/components/schemas/IConnectorModule'
        configs:
          type: array
          items:
            $ref: '#/components/schemas/IConnectorConfig'
    IConnectorModule:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        version:
          type: string
        status:
          type: integer
          format: int32
    Data:
      type: object
      properties:
        status:
          type: integer
          format: int32
        collectStatus:
          type: integer
          format: int32
        version:
          type: string
        modules:
          type: array
          items:
            $ref: '#/components/schemas/Module'
    IConnectorInfoParam:
      type: object
      properties:
        connectorId:
          type: string
        dateTime:
          type: integer
          format: int64
        data:
          $ref: '#/components/schemas/Data'
    Module:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        status:
          type: integer
          format: int32
    IConnectorInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        connectorId:
          type: string
        status:
          type: integer
          format: int32
        collectStatus:
          type: integer
          format: int32
        version:
          type: string
        dateTime:
          type: integer
          format: int64
        modules:
          type: array
          items:
            $ref: '#/components/schemas/IConnectorModule'
        configs:
          type: array
          items:
            $ref: '#/components/schemas/IConnectorConfig'
    ClientQueryParam:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tenantId:
          type: string
    PageParam:
      required:
        - pageNumber
        - pageSize
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
