server:
  port: 8887

kafka:
  ssl:
    location:
      truststore: /certs/kafka.server.truststore.jks
      keystore: /certs/kafka.server.keystore.jks
    password: 123456

spring:
  kafka:
    bootstrap-servers: kafka:9093
    security:
      protocol: "ssl"
    ssl:
      trust-store-location: file:${kafka.ssl.location.truststore}
      trust-store-password: ${kafka.ssl.password}
      key-store-location: file:${kafka.ssl.location.keystore}
      key-store-password: ${kafka.ssl.password}
      key-password: ${kafka.ssl.password}

    producer:
      # 失败重试次数
      retries: 3
      # 每次批量发送消息的数量
      batch-size: 16
      # 缓存容量
      buffer-memory: 33554432
      # 编解码
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: group-dafult
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

webclient:
  maxInMemorySize: 10485760
  connectTimeout: 10000
  responseTimeout: 10000
  maxConnections: 1000
  maxPendingCount: 3000