server:
  port: 8887
  ssl:
    enabled: true
    key-store-type: jks
    key-store: /Users/hakurei/Projects/hello-kafka/http-ssl/message-handler/message-handler-server.jks
    key-store-password: 123456
    key-alias: message-handler-server
    trust-store: /Users/hakurei/Projects/hello-kafka/http-ssl/message-handler/message-handler-server.jks
    trust-store-password: 123456
    trust-store-type: jks
    client-auth: need
    trust-store-provider: SUN

kafka:
  ssl:
    location:
      truststore: /Users/hakurei/Projects/hello-kafka/message-handler/src/main/resources/kafka.server.truststore.jks
      keystore: /Users/hakurei/Projects/hello-kafka/message-handler/src/main/resources/kafka.server.keystore.jks
    password: 123456

spring:
  kafka:
    bootstrap-servers: localhost:9093
    security:
      protocol: "ssl"
    ssl:
      trust-store-location: file:${kafka.ssl.location.truststore}
      trust-store-password: ${kafka.ssl.password}
      key-store-location: file:${kafka.ssl.location.keystore}
      key-store-password: ${kafka.ssl.password}
      key-password: ${kafka.ssl.password}

    producer:
      # 失败重试次数
      retries: 3
      # 每次批量发送消息的数量
      batch-size: 16
      # 缓存容量
      buffer-memory: 33554432
      # 编解码
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: group-dafult
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

webclient:
  maxInMemorySize: 10485760
  connectTimeout: 10000
  responseTimeout: 10000
  maxConnections: 1000
  maxPendingCount: 3000

configuration-service:
  ssl-client:
    client-file: /Users/hakurei/Projects/hello-kafka/http-ssl/configuration-service/configuration-service-client.jks
    client-type: JKS
    client-password: 123456

pcf-service:
  ssl-client:
    client-file: /Users/hakurei/Projects/hello-kafka/http-ssl/configuration-service/configuration-service-client.jks
    client-type: JKS
    client-password: 123456